path: C:/Users/mikha/OneDrive/Desktop/CV_MTUCI

train: data/processed/train2000_images.txt
val:   data/processed/val_images.txt
test:  data/processed/test_images.txt

nc: 9

names:
  0: person
  1: bicycle
  2: car
  3: motorcycle
  4: bus
  5: truck
  6: backpack
  7: handbag
  8: suitcase